### ISSUE TITLE
Error: Sorry, no matching options

### ISSUE THREAD

**Issue by aerni** [aryehraber/statamic-font-awesome#10]
I followed the installation instructions. But I only get a `Sorry, no matching options.` error. Any hints?

<img width="808" alt="Screenshot 2021-03-02 at 12 19 21 PM" src="https://user-images.githubusercontent.com/23167701/109641042-880c3180-7b51-11eb-8702-8e79d8534a4d.png">

**Comment by aerni** [comment]
Sorry, my bad. I added the Kit ID rather than the Kit URL 🤦🏻‍♂️

**Comment by aryehraber** [comment]
@aerni All good 😊 Thanks for following up, glad it's all still working!
