### ISSUE TITLE
Add ability to add classes

### ISSUE THREAD

**Issue by aerni** [aryehraber/statamic-font-awesome#12]
It would be great if we could add additional classes to the icon output. This is useful for things like [Fixed Width Icons](https://fontawesome.com/how-to-use/on-the-web/styling/fixed-width-icons).

I'm happy to submit a PR.

**Comment by aryehraber** [comment]
Added in latest release thanks to your PR!

**Comment by aerni** [comment]
Awesome. Thanks.
