### ISSUE TITLE
Super slow loading times

### ISSUE THREAD

**Issue by aerni** [aryehraber/statamic-font-awesome#14]
The fieldtype is super slow. It's taking up to 20 seconds to load the icons. Can we cache this somehow?

**Comment by aryehraber** [comment]
Hey @aerni, that doesn't sound great... Tbh I haven't used this addon in a long time so I'm not sure when I'll be able to take a closer look. I'm open to a PR if you have time to track down what is causing the delay, otherwise I'll try and find some time to take a look myself in the coming week(s).

**Comment by aryehraber** [comment]
Tried having a closer look today but it seems FA has changed how a few things work and my previous Font Kits have been deleted meaning I can't use it for testing the addon anymore (my yearly subscription has expired). 

Since I no longer actively use this addon myself I don't think I'll be able to work on it any further, feel free to fork it if you'd like to continue with it!

**Comment by aerni** [comment]
I can look into this. If it's a simple fix, would you accept a PR? If it's a bigger thing, I'll refactor and release afresh.

**Comment by aryehraber** [comment]
Happy to accept a PR 👍 but will have to rely on you to do the testing as I can't check it on my end.

**Comment by aerni** [comment]
I started diving into it and am now actually working on a complete rewrite with additional features. If you don't plan to further develop this addon, would you be so kind to archive this repo and package on packagist and refer to my new addon?

**Comment by aryehraber** [comment]
Sounds good 👍 

Let me know in this issue when everything is up and running on Packagist + Statamic Marketplace. Good luck!

**Comment by aerni** [comment]
Done! https://statamic.com/addons/aerni/font-awesome

**Comment by aryehraber** [comment]
I've updated the README and set Packagist to point to your addon instead. Good luck!
