### ISSUE TITLE
Cant seem to load any of the icons in the cp 

### ISSUE THREAD

**Issue by PilauGrice** [aryehraber/statamic-font-awesome#15]
I can seem to get any of the icons to load in the picker on the CP just says sorry no matching options any ideas

**Comment by Gricey404** [comment]
<img width="778" alt="Screenshot 2021-11-03 at 08 29 08" src="https://user-images.githubusercontent.com/54929567/140032296-c4ca7187-376e-4dd9-9541-5b8b68a8ed18.png">
