### ISSUE TITLE
Update to 5.X

### ISSUE THREAD

**Issue by Pfeifakopf** [aryehraber/statamic-font-awesome#5]
Hi,
could you update the addon to a current version?
Thanks for your work!

**Comment by aryehraber** [comment]
Hi @Pfeifakopf, there are currently no plans to update to FA v5+ as I haven't used FA for quite a while... Would be happy to accept a PR!

**Comment by aryehraber** [comment]
Font Awesome 5 support has been added for the Statamic 3 version:

https://github.com/aryehraber/statamic-font-awesome/tree/statamic-3
