### ISSUE TITLE
Component font_awesome-fieldtype does not exist.

### ISSUE THREAD

**Issue by dwainscheeren** [aryehraber/statamic-font-awesome#6]
Getting the error `Component font_awesome-fieldtype does not exist.` on a fresh v3 install of Statamic

![](https://puu.sh/FzXcp/722171e277.png)

**Comment by aryehraber** [comment]
Hi @dwainscheeren, can you confirm that the addon is correctly installed? The files should exist in `vendor/aryehraber/statamic-font-awesome/*`.

**Comment by dwainscheeren** [comment]
Yep. 

![](https://puu.sh/FzXGa/7ec57a5bd1.png)

I also published the config for it and entered a valid `kit_url` I also cleared the cache

**Comment by aryehraber** [comment]
Hmm interesting, thanks for confirming! Will do some more testing on my end to see if I can reproduce from a fresh install.

For now, can you try copy the dist js build and paste inside:
```
public/vendor/aryehraber/statamic-font-awesome/js/font_awesome-fieldtype.js
```

File can be found [here](https://github.com/aryehraber/statamic-font-awesome/blob/statamic-3/resources/dist/js/font_awesome-fieldtype.js) or copy from vendor folder.

**Comment by dwainscheeren** [comment]
I have done that, now its working! So it didnt copied that file automatic, so you know the problem.

**Comment by aryehraber** [comment]
Perfect, thanks for testing and getting back to me. That narrows things down 👌

**Comment by aryehraber** [comment]
Turns out this wasn't a bug, I simply misread the docs... 🙈 

I've updated the README now, for future reference the JS assets need to be published together with the config file: 

```
php artisan vendor:publish --provider="AryehRaber\FontAwesome\FontAwesomeServiceProvider"
```
